FROM golang:1.22.4-alpine3.20

# Go to a temporary directory until we install all the dependencies
RUN mkdir -p /app/temp
WORKDIR /app/temp

# Install the necessary packages
RUN apk update && apk add --no-cache \
    bash=5.2.26-r0 \
    wget=1.24.5-r0 \
    git=2.45.2-r0 \
    openssh=9.7_p1-r3 \
    rclone=1.66.0-r3

# Install task
RUN wget https://github.com/go-task/task/releases/download/v3.34.1/task_linux_amd64.tar.gz && \
    tar -xzf task_linux_amd64.tar.gz && \
    mv ./task /usr/local/bin/task && \
    chmod 777 /usr/local/bin/task

# Install GitHub CLI
RUN wget https://github.com/cli/cli/releases/download/v2.46.0/gh_2.46.0_linux_amd64.tar.gz && \
    tar -xzf gh_2.46.0_linux_amd64.tar.gz && \
    mv gh_2.46.0_linux_amd64/bin/gh /usr/local/bin/gh && \
    chmod 777 /usr/local/bin/gh

# Delete the temporary directory and go to the app directory
RUN rm -rf /app/temp
WORKDIR /app

# Add the startup script on every bash session
COPY scripts/startup.sh /usr/local/bin/startup.sh
RUN echo "\n\n" >> /root/.bashrc && \
    cat /usr/local/bin/startup.sh >> /root/.bashrc

# Expose the port 22 and keep the container running
EXPOSE 22
CMD ["tail", "-f", "/dev/null"]
