version: "3"

dotenv: [".env"]

tasks:
  on:
    cmds:
      - docker compose up -d --build
      - docker compose exec app /bin/bash

  off:
    cmd: docker compose down

  reon:
    cmds:
      - task off
      - task on

  build:
    deps:
      - clean
    cmds:
      - task fmt
      - go build -o ./dist/s3ftp ./cmd/s3ftp/.

  serve:
    cmd: ./dist/s3ftp

  run:
    cmds:
      - task build
      - task serve

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  test:
    cmds:
      - task fmt
      - go test ./...

  clean:
    cmds:
      - rm -rf ./tmp
      - rm -rf ./dist

  fixperms:
    cmd: ./scripts/fixperms.sh
